# Generated by Django 5.2.7 on 2025-10-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tanque', models.CharField(max_length=50)),
                ('precio', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=50)),
                ('imagen', models.URLField()),
            ],
        ),
    ]
