# Generated by Django 5.2.7 on 2025-10-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TankStoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanque',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
