# Generated by Django 5.2.7 on 2025-10-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TankStoreApp', '0002_alter_tanque_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
