# Generated by Django 5.2.7 on 2025-10-18 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TankStoreApp', '0003_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanque',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TankStoreApp.categoria'),
            preserve_default=False,
        ),
    ]
