# Generated by Django 5.2.7 on 2025-10-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TankStoreApp', '0004_tanque_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanque',
            name='pais',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
